---
- name: gnome-dconf role
  tags:
    - gnome-dconf
  block:

  # assert
  - name: Assertions
    ansible.builtin.assert:
      that:
        - gnome_dconf_user != None
        - ansible_os_family is defined

  # make sure user exists
  - name: Check if user exists {{ gnome_dconf_user }}
    command: "getent passwd {{ gnome_dconf_user }}"
    changed_when: false

  # install psutil
  - name: Apt install psutil requirement
    when: ansible_os_family == "debian"
    become: true
    ansible.builtin.apt:
      name: python3-psutil
      state: present

  # normal user
  - when: gnome_dconf_user != "global"
    become: true
    become_user: "{{ gnome_dconf_user }}"
    ansible.builtin.import_tasks: "{{ role_path }}/tasks/{{ gnome_dconf_subtask }}"