---
- name: gnome-dconf role
  tags:
    - gnome-dconf
  block:

  # assert
  - name: Assertions
    ansible.builtin.assert:
      that:
        - gnome_dconf_user != None
        - ansible_os_family is defined

  # make sure user exists
  - name: Check if user exists {{ gnome_dconf_user }}
    command: "getent passwd {{ gnome_dconf_user }}"
    changed_when: false

  # install psutil
  - name: Apt install psutil requirement
    when: ansible_os_family == "debian"
    become: true
    ansible.builtin.apt:
      name: python3-psutil
      state: present

  # assertions
  - name: Assertions for gnome_dconf_configs
    loop: "{{ gnome_dconf_configs }}"
    loop_control:
      loop_var: __gnome_dconf_item
    ansible.builtin.assert:
      that:
      - __gnome_dconf_item.key != None
      - __gnome_dconf_item.value != None

  # apply
  - when: gnome_dconf_configs | length > 1
    name: Apply settings to dconf
    become: true
    become_user: "{{ gnome_dconf_user }}"
    loop: "{{ gnome_dconf_configs }}"
    loop_control:
      loop_var: __gnome_dconf_item
    community.general.dconf:
      key: "{{ __gnome_dconf_item.key }}"
      value: "{{ __gnome_dconf_item.value }}"