# /org/gnome/shell
- block:

  - name: remember-mount-password
    community.general.dconf:
      key: /org/gnome/shell/remember-mount-password
      value: "false" # keine cryptsetup passwörter speichern

# /org/gtk/settings
- block:

  - name: sort-directories-first
    community.general.dconf:
      key: /org/gtk/settings/file-chooser/sort-directories-first
      value: "true"

# /org/gnome/desktop
- block:

  - name: autorun-never
    community.general.dconf:
      key: /org/gnome/desktop/media-handling/autorun-never # If set to true, then Nautilus will never prompt nor autorun/autostart programs when a medium is inserted.
      value: "true"

  - name: old-files-age
    community.general.dconf:
      key: /org/gnome/desktop/privacy/old-files-age # # Number of days to keep trash and temporary files
      value: "7"

  - name: remove-old-trash-files
    community.general.dconf:
      key: /org/gnome/desktop/privacy/remove-old-trash-files # Whether to remove old files from the trash automatically
      value: "true"

  - name: remove-old-temp-files
    community.general.dconf:
      key: /org/gnome/desktop/privacy/remove-old-temp-files # Whether to remove old temporary files automatically
      value: "true"

  - name: idle-delay for 'all'
    community.general.dconf:
      key: /org/gnome/desktop/session/idle-delay # The number of seconds of inactivity before the session is considered idle.
      value: "0"

  - name: lock-enabled
    community.general.dconf:
      key: /org/gnome/desktop/screensaver/lock-enabled # Set this to TRUE to lock the screen when the screensaver goes active.
      value: "false"

# /org/gnome/settings-daemon
- block:

  - name: idle-dim
    community.general.dconf:
      key: /org/gnome/settings-daemon/plugins/power/idle-dim # If the screen should be dimmed to save power when the computer is idle.
      value: "true"

  - name: sleep-inactive-battery-type
    community.general.dconf:
      key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type # Whether to hibernate, suspend or do nothing when inactive
      value: "'suspend'"
  
  - name: sleep-inactive-ac-type
    community.general.dconf:
      key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
      value: "'nothing'"
  
  - name: sleep-inactive-ac-timeout
    community.general.dconf:
      key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout" # The amount of time in seconds the computer on AC power needs to be inactive before it goes to sleep. A value of 0 means never.
      value: "0"
      
# /org/gnome/calculator
- block:

  - name: calculator/refresh-interval
    community.general.dconf:
      key: "/org/gnome/calculator/refresh-interval"
      value: "0"